backend:
  name: github
  repo: constructions-incongrues/empilements
  branch: main
  site_domain: 1a522206-9642-4c26-bac4-280770cfbff4
  
media_folder: static/files
public_folder: files

collections:
  - label: "Contents"
    name: "contents"
    files:
      - label: "Empilement"
        name: "empilement"
        file: "content/_index.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'markdown', required: false }
          - label: "Cover"
            name: "cover"
            widget: "file"
            media_library:
              choose_url: false
          - label: Curators
            name: curators
            widget: list
            summary: "{{name}}"
            fields:
              - {label: Name, name: name, widget: string}
          - label: Tracks
            name: tracks
            widget: list
            summary: "{{artist}} - {{title}}"
            fields:
              - {label: Artist, name: artist, widget: string}
              - {label: Title, name: title, widget: string}
              - label: File
                name: file
                widget: file
                media_library:
                  choose_url: false
